package br.com.ForTeethDentalCare.dataStore

data class Address(
    var cep1: String,
    var enderecoNumero1: String,
    var complemento1: String,
    var rua1: String,
    var bairro1: String,
    var cidade1: String,
    var estado1: String,
    var cep2: String,
    var enderecoNumero2: String,
    var complemento2: String,
    var rua2: String,
    var bairro2: String,
    var cidade2: String,
    var estado2: String,
    var cep3: String,
    var enderecoNumero3: String,
    var complemento3: String,
    var rua3: String,
    var bairro3: String,
    var cidade3: String,
    var estado3: String,
    var primeiroEndereco: String,
    var segundoEndereco: String,
    var terceiroEndereco: String,
)
